/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DefaultNavigationInfoPanelTest2.java
 *
 * Created on 22.May.2014, 16:22:12
 */
package tr.edu.ege.cs.egenav.test;

/**
 *
 * @author Özgün Yılmaz
 */
public class DefaultNavigationInfoPanelTest2 extends javax.swing.JFrame {

    /** Creates new form DefaultNavigationInfoPanelTest2 */
    public DefaultNavigationInfoPanelTest2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defaultNavigationInformationPanel1 = new tr.edu.ege.cs.egenav.ui.DefaultNavigationInformationPanel2();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(defaultNavigationInformationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(defaultNavigationInformationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DefaultNavigationInfoPanelTest2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tr.edu.ege.cs.egenav.ui.DefaultNavigationInformationPanel2 defaultNavigationInformationPanel1;
    // End of variables declaration//GEN-END:variables
}
