/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MapFrameTest.java
 *
 * Created on 02.May.2014, 16:36:57
 */
package tr.edu.ege.cs.egenav.test;

import tr.edu.ege.cs.egenav.Location;
import tr.edu.ege.cs.egenav.GSMMapURL;
import tr.edu.ege.cs.egenav.GeoPoint;
import tr.edu.ege.cs.egenav.MapSize;
import tr.edu.ege.cs.egenav.ui.MapPanel;

/**
 *
 * @author Özgün Yılmaz
 */
public class MapFrameTest extends javax.swing.JFrame {

    /** Creates new form MapFrameTest */
    public MapFrameTest() {
        initComponents();
        GSMMapURL m=new GSMMapURL();
        m.setCenter(new Location(new GeoPoint(40,30)));
        m.setZoom(6);
        m.setMapSize(new MapSize(500,500));
        
        
        
        MapPanel mp=new MapPanel(m);
        
        mp.updateLocation(new Location(new GeoPoint(42,32)));
        mp.updateLocation(new Location(new GeoPoint(38,28)));
        mp.updateLocation(new Location(new GeoPoint(39,33)));
        
        getContentPane().add(mp);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MapFrameTest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
